export type Hour = {
  number: number;
  enabled: boolean;
};

export type DayData = {
  [key: string]: Array<Hour>;
};

export const calendarTemplate: DayData = {
  monday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
  tuesday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
  wednesday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
  thursday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
  friday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
  saturday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
  sunday: [
    { number: 7, enabled: true },
    { number: 8, enabled: true },
    { number: 9, enabled: true },
    { number: 10, enabled: true },
    { number: 11, enabled: true },
    { number: 12, enabled: true },
    { number: 13, enabled: true },
    { number: 14, enabled: true },
    { number: 15, enabled: true },
    { number: 16, enabled: true },
    { number: 17, enabled: true },
    { number: 18, enabled: true },
    { number: 19, enabled: true },
    { number: 20, enabled: true },
    { number: 21, enabled: true },
    { number: 22, enabled: true },
  ],
};
