version: '3.7'
name: express-cash-backend-production
services:
  express-cash-backend:
    container_name: express-cash-backend
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - '9101:9101'
    networks:
      - express-cash_network
    volumes:
      - ./uploads:/app/uploads

networks:
  express-cash_network:
